<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<NoWarn>$(NoWarn);NU5128</NoWarn>
    <PackageId>Tenowg.MongoOptions</PackageId>
    <Authors>Craig Russell</Authors>
	<PackageProjectUrl>https://github.com/tenowg/MongoOptions</PackageProjectUrl>
	<PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
	<RepositoryUrl>https://github.com/tenowg/MongoOptions</RepositoryUrl>
	<RepositoryType>git</RepositoryType>
    <Description>A resilient, keyed configuration provider using MongoDB and IMemoryCache.</Description>
    <PackageTags>mongodb;dotnet10;options;configuration;csharp14</PackageTags>
	<PackageReadmeFile>README.md</PackageReadmeFile>

	<GeneratePackageOnBuild Condition="'$(Configuration)' == 'Release'">true</GeneratePackageOnBuild>
	<GeneratePackageOnBuild Condition="'$(Configuration)' == 'Debug'">false</GeneratePackageOnBuild>

	<PublishAot>false</PublishAot>
	<IsAotCompatible>true</IsAotCompatible>

	<EnableConfigurationBindingGenerator>true</EnableConfigurationBindingGenerator>
	  
	<Configurations>Debug;Release</Configurations>
  </PropertyGroup>
  <PropertyGroup>
	<PublishRepositoryUrl>true</PublishRepositoryUrl>
	<EmbedUntrackedSources>true</EmbedUntrackedSources>
	<IncludeSymbols>true</IncludeSymbols>
	<SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Templates\MongoModel\MongoModel.cs" />
    <Compile Remove="Templates\MongoSubModel\MongoSubModel.cs" />
  </ItemGroup>
  <ItemGroup>
	<None Include="CHANGELOG.md" Pack="true" PackagePath="\" />
	<None Include="MongoOptions.csproj.user" />
	<None Include="README.md" Pack="true" PackagePath="\" />
	<None Include="LICENSE.txt" Pack="true" PackagePath="\" />
  </ItemGroup>
  <ItemGroup>
	<FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
	<PackageReference Include="MinVer" Version="7.0.0">
		<PrivateAssets>all</PrivateAssets>
		<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	</PackageReference>

    <PackageReference Include="MongoDB.Driver" Version="3.8.0" />

    <PackageReference Include="SharpCompress" Version="0.48.0" />

    <PackageReference Include="Snappier" Version="1.3.1" />
  </ItemGroup>
  <ItemGroup>
	<None Include="..\MongoOptions.Generator\bin\$(Configuration)\netstandard2.0\MongoOptions.Generator.dll" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false" />
  </ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\MongoOptions.Generator\MongoOptions.Generator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
	</ItemGroup>
</Project>