<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <PackageId>Tenowg.MongoOptions</PackageId>
    <Authors>Craig Russell</Authors>
	<PackageProjectUrl>https://github.com/tenowg/MongoOptions</PackageProjectUrl>
	<PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
	<RepositoryUrl>https://github.com/tenowg/MongoOptions</RepositoryUrl>
	<RepositoryType>git</RepositoryType>
    <Description>A resilient, keyed configuration provider using MongoDB and IMemoryCache.</Description>
    <PackageTags>mongodb;dotnet10;options;configuration;csharp14</PackageTags>
	<PackageReadmeFile>README.md</PackageReadmeFile>

	<GeneratePackageOnBuild Condition="'$(Configuration)' == 'Release'">true</GeneratePackageOnBuild>

	<GeneratePackageOnBuild Condition="'$(Configuration)'=='LocalRelease'">true</GeneratePackageOnBuild>

	<GeneratePackageOnBuild Condition="'$(Configuration)' == 'Debug'">false</GeneratePackageOnBuild>
	<PackageOutputPath>I:\LocalNuget\</PackageOutputPath>
	<Configurations>Debug;Release;LocalRelease</Configurations>
  </PropertyGroup>
	<PropertyGroup>
		<PublishRepositoryUrl>true</PublishRepositoryUrl>
		<EmbedUntrackedSources>true</EmbedUntrackedSources>
		<IncludeSymbols>true</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
	</PropertyGroup>
	<ItemGroup>
	  <None Include="CHANGELOG.md" Pack="true" PackagePath="\" />
	</ItemGroup>

    <ItemGroup>
	    <None Include="README.md" Pack="true" PackagePath="\" />
		<None Include="LICENSE.txt" Pack="true" PackagePath="\" />
    </ItemGroup>
	
  <ItemGroup>
	<PackageReference Include="MinVer" Version="7.0.0">
		<PrivateAssets>all</PrivateAssets>
		<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	</PackageReference>
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="10.0.2" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.2" />
    <PackageReference Include="MongoDB.Driver" Version="3.6.0" />
  </ItemGroup>

</Project>